# Generated by Django 2.0.5 on 2019-03-05 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def generate_default_rows(apps, schema_editor):
    Plan = apps.get_model('qa', 'Plan')
    def_plan = Plan()
    def_plan.name = 'Free'
    def_plan.save()

    Service = apps.get_model('qa', 'Service')
    def_service = Service()
    def_service.cd = '00001'
    def_service.name = 'QA'
    def_service.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0113_auto_20190305_1131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='plan name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'Plan',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=64, null=True, verbose_name='service code')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='service name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'Service',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VendorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorplan_plan', to='qa.Plan', verbose_name='Plan')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorplan_vendor', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'VendorPlan',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorservice_service', to='qa.Service', verbose_name='Service')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorservice_vendor', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'VendorService',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='last name')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='first name')),
                ('last_name_kana', models.CharField(max_length=64, null=True, verbose_name='last name kana')),
                ('first_name_kana', models.CharField(max_length=64, null=True, verbose_name='first name kana')),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='email')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_vendoruser_user', to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_vendoruser_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'VendorUser',
                'permissions': (),
            },
        ),
        migrations.RunPython(generate_default_rows),
    ]
