# Generated by Django 2.0.5 on 2019-03-12 02:01

from django.db import migrations, models
import django.db.models.deletion


def generate_default_rows(apps, schema_editor):
    NotificationService = apps.get_model('qa', 'NotificationService')
    def_notificationservice = NotificationService()
    def_notificationservice.name = 'Email'
    def_notificationservice.save()

    def_notificationservice = NotificationService()
    def_notificationservice.name = 'Slack'
    def_notificationservice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_vendoruser_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='notification service name')),
                ('icon', models.CharField(max_length=256, null=True, verbose_name='notification service icon')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'NotificationService',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_value', models.IntegerField(default=0, verbose_name='setting value')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('notification_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsetting_service', to='qa.NotificationService', verbose_name='NotificationService')),
                ('vendor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsetting_vendor_user', to='qa.VendorUser', verbose_name='VendorUser')),
            ],
            options={
                'verbose_name': 'NotificationSetting',
                'permissions': (),
            },
        ),
        migrations.RunPython(generate_default_rows),
    ]
