# Generated by Django 2.0.5 on 2019-03-12 08:32

from django.db import migrations, models
import django.db.models.deletion


def generate_default_rows(apps, schema_editor):
    CouponType = apps.get_model('qa', 'CouponType')
    def_coupon_type = CouponType()
    def_coupon_type.name = 'text'
    def_coupon_type.save()

    def_coupon_type = CouponType()
    def_coupon_type.name = 'url'
    def_coupon_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_notificationservice_notificationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='coupon name')),
                ('qr_path', models.CharField(max_length=256, verbose_name='qr coupon path')),
                ('data', models.CharField(max_length=256, null=True, verbose_name='coupon data contents')),
                ('style', models.CharField(max_length=256, null=True, verbose_name='coupon data contents')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='valid from datetime')),
                ('valid_until', models.DateTimeField(null=True, verbose_name='valid until datetime')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'NotificationService',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='coupon type name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
            ],
            options={
                'verbose_name': 'CouponType',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_type', to='qa.CouponType', verbose_name='CouponType'),
        ),
        migrations.RunPython(generate_default_rows),
    ]
