# Generated by Django 2.0.5 on 2019-03-19 04:44

import apps.qa.models.coupon
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_coupon_vendor_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'permissions': (), 'verbose_name': 'Coupon'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='qr_path',
        ),
        migrations.AddField(
            model_name='coupon',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=apps.qa.models.coupon.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid from datetime'),
        ),
    ]
