# Generated by Django 2.0.5 on 2019-03-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20190319_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
