# Generated by Django 2.0.5 on 2019-03-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20190325_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.CharField(max_length=2048, null=True, verbose_name='question options'),
        ),
    ]
