# Generated by Django 2.0.5 on 2019-04-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20190401_1448'),
        ('qa', '0010_question_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_enduserquestionnaire_end_user', to='core.EndUser', verbose_name='end_user')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_enduserquestionnaire_questionnaire', to='qa.Questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'EndUserQuestionnaire',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048, null=True, verbose_name='question content')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_response_end_user', to='core.EndUser', verbose_name='end_user')),
                ('end_user_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_response_end_user_questionnaire', to='qa.EndUserQuestionnaire', verbose_name='end_user_questionnaire')),
                ('questionnaire_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_response_questionnaire_question', to='qa.QuestionnaireQuestion', verbose_name='questionnaire_question')),
            ],
            options={
                'verbose_name': 'Response',
                'permissions': (),
            },
        ),
    ]
