# Generated by Django 2.0.5 on 2019-04-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_enduserquestionnaire_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoruser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active flg'),
        ),
    ]
