# Generated by Django 2.0.5 on 2019-04-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20190419_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenbayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_token', models.CharField(max_length=128, null=True, verbose_name='last name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_active', models.BooleanField(default=False, verbose_name='active flg')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete flg')),
                ('vendor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_senbayuser_vendor_user', to='qa.VendorUser')),
            ],
            options={
                'verbose_name': 'SenbayUser',
                'permissions': (),
            },
        ),
    ]
