# Generated by Django 2.0.5 on 2019-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_senbayuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senbayuser',
            name='jwt_token',
            field=models.CharField(max_length=1024, null=True, verbose_name='last name'),
        ),
    ]
