# Generated by Django 2.0.5 on 2019-05-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_auto_20190420_2213'),
        ('qa', '0012_auto_20190422_1725'),
    ]

    operations = [
    ]
