# Generated by Django 2.0.5 on 2019-05-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20190501_1606'),
        ('qa', '0016_vendorbusinesspartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBusinessPartnerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='company name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorbusinesspartnertag_vendor_business_partner_tag', to='core.Vendor', verbose_name='Vendor_BusinessPartnerTag')),
            ],
            options={
                'verbose_name': 'VendorBusinessPartnerTag',
                'permissions': (),
            },
        ),
    ]
