# Generated by Django 2.0.5 on 2019-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_vendorbusinesspartnertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbusinesspartnertag',
            name='cd',
            field=models.CharField(max_length=256, null=True, verbose_name='tag code'),
        ),
        migrations.AlterField(
            model_name='vendorbusinesspartnertag',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='tag name'),
        ),
    ]
