# Generated by Django 2.0.5 on 2019-05-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0019_vendorbusinesspartner_tag_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='valid_from',
            field=models.DateTimeField(default='2019-05-07 13:23:05', verbose_name='valid from datetime'),
        ),
    ]
