# Generated by Django 2.0.5 on 2019-05-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20190509_1615'),
        ('qa', '0021_auto_20190507_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='message subject')),
                ('message_text', models.CharField(default='', max_length=2048, verbose_name='question text')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_message_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'Message',
                'permissions': (),
            },
        ),
    ]
