# Generated by Django 2.0.5 on 2019-05-14 02:09

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0024_auto_20190510_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=redactor.fields.RedactorField(default='', max_length=2048, verbose_name='question text'),
        ),
    ]
