# Generated by Django 2.0.5 on 2019-05-16 07:40

from django.db import migrations, models


def generate_default_rows(apps, schema_editor):
    QuestionType = apps.get_model('qa', 'QuestionType')
    def_question_type = QuestionType()
    def_question_type.name = 'registration'
    def_question_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0026_auto_20190516_1640'),
    ]

    operations = [
        migrations.RunPython(generate_default_rows),
    ]
