# Generated by Django 2.0.5 on 2019-05-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20190521_1636'),
        ('qa', '0027_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponclaim_coupon', to='qa.Coupon', verbose_name='Coupon')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponclaim_end_user', to='core.EndUser', verbose_name='end_user')),
            ],
            options={
                'verbose_name': 'CouponClaim',
                'permissions': (),
            },
        ),
    ]
