# Generated by Django 2.0.5 on 2019-05-22 08:56

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0028_couponclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
