# Generated by Django 2.0.5 on 2019-06-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0029_auto_20190522_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='end_user_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.EndUserQuestionnaire', verbose_name='end_user_questionnaire'),
        ),
    ]
