# Generated by Django 2.0.5 on 2019-06-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0030_auto_20190604_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='end_user_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response', to='qa.EndUserQuestionnaire', verbose_name='end_user_questionnaire'),
        ),
    ]
