# Generated by Django 2.0.5 on 2019-06-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20190609_1638'),
        ('qa', '0031_auto_20190604_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='product category name')),
                ('code', models.CharField(max_length=256, null=True, verbose_name='product category code')),
                ('memo', models.TextField(null=True, verbose_name='memo')),
                ('sales_price', models.IntegerField(null=True, verbose_name='sales price')),
                ('receiving_price', models.IntegerField(null=True, verbose_name='receiving price')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'Product',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='product category name')),
                ('code', models.CharField(max_length=256, null=True, verbose_name='product category code')),
                ('memo', models.TextField(null=True, verbose_name='memo')),
                ('display_order_num', models.IntegerField(null=True, verbose_name='display order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcategory_vendor_product_category', to='core.Vendor', verbose_name='Vendor_ProductCategory')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReceivingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('price', models.IntegerField(null=True, verbose_name='sales price')),
                ('issue_number', models.CharField(max_length=256, null=True, verbose_name='issue number')),
                ('track_number', models.CharField(max_length=256, null=True, verbose_name='track number')),
                ('scheduled_dt', models.DateTimeField(null=True, verbose_name='scheduled datetime')),
                ('stats', models.IntegerField(null=True, verbose_name='status')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('business_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivinghistory_bp_receiving_history', to='qa.VendorBusinessPartner', verbose_name='BP_Receiving_History')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivinghistory_product_receiving_history', to='qa.Product', verbose_name='Product_Receiving_History')),
            ],
            options={
                'verbose_name': 'Receiving History',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShippingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('price', models.IntegerField(null=True, verbose_name='sales price')),
                ('issue_number', models.CharField(max_length=256, null=True, verbose_name='issue number')),
                ('track_number', models.CharField(max_length=256, null=True, verbose_name='track number')),
                ('scheduled_dt', models.DateTimeField(null=True, verbose_name='scheduled datetime')),
                ('stats', models.IntegerField(null=True, verbose_name='status')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('business_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippinghistory_bp_shipping_history', to='qa.VendorBusinessPartner', verbose_name='BP_Shipping_History')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippinghistory_product_shipping_history', to='qa.Product', verbose_name='Product_Shipping_History')),
            ],
            options={
                'verbose_name': 'Shipping History',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('memo', models.TextField(null=True, verbose_name='memo')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_stock', to='qa.Product', verbose_name='Product_Stock')),
            ],
            options={
                'verbose_name': 'Stock',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StockSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='space name')),
                ('code', models.CharField(max_length=256, null=True, verbose_name='space code')),
                ('memo', models.TextField(null=True, verbose_name='memo')),
                ('display_order_num', models.IntegerField(null=True, verbose_name='display order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockspace_vendor_stock_space', to='core.Vendor', verbose_name='Vendor_StockSpace')),
            ],
            options={
                'verbose_name': 'StockSpace',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_category_product', to='qa.ProductCategory', verbose_name='ProductCategory_Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_space_product', to='qa.StockSpace', verbose_name='StockSpace_Product'),
        ),
    ]
