# Generated by Django 2.0.5 on 2019-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0034_auto_20190609_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_options',
        ),
    ]
