# Generated by Django 2.0.5 on 2019-06-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0035_remove_question_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.CharField(max_length=2048, null=True, verbose_name='question options'),
        ),
    ]
