# Generated by Django 2.0.5 on 2019-06-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0037_default_charset'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='template name')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questionnairetemplate_questionnaire', to='qa.Questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Template',
                'permissions': (),
            },
        ),
    ]
