# Generated by Django 2.0.5 on 2019-06-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0039_remove_questionnairetemplate_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, verbose_name='display order')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questionnairetemplatequestion_question', to='qa.Question', verbose_name='question')),
                ('questionnaire_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questionnairetemplatequestion_questionnaire', to='qa.QuestionnaireTemplate', verbose_name='questionnaire template')),
            ],
            options={
                'verbose_name': 'Questionnaire Template Question',
                'permissions': (),
            },
        ),
    ]
