# Generated by Django 2.0.5 on 2019-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0040_questionnairetemplatequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_options',
            field=models.CharField(default=None, max_length=2048, null=True, verbose_name='question options'),
        ),
    ]
