# Generated by Django 2.0.5 on 2019-07-30 07:09

import apps.qa.models.coupon
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0043_questionnaretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=apps.qa.models.coupon.get_formatted_now, verbose_name='valid from datetime'),
        ),
    ]
