# Generated by Django 2.0.5 on 2019-10-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False, verbose_name='active flg')),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='app_id')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='regist datetime')),
            ],
            options={
                'verbose_name': 'Bot',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BotScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageflow.Bot')),
            ],
            options={
                'verbose_name': 'BotScenario',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_content', models.TextField(default='', null=True, verbose_name='json content')),
                ('options', models.CharField(default=None, max_length=2048, null=True, verbose_name='options')),
                ('display_order', models.IntegerField(default=-1, null=True, verbose_name='display_order')),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='app_id')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
            ],
            options={
                'verbose_name': 'Message',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('display_order', models.IntegerField(default=-1, null=True, verbose_name='display_order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='regist datetime')),
            ],
            options={
                'verbose_name': 'MessageBlock',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='message type name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
            ],
            options={
                'verbose_name': 'MessageType',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='app_id')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='regist datetime')),
            ],
            options={
                'verbose_name': 'Scenario',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='messageblock',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageflow.Scenario', verbose_name='scenario'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageflow.MessageBlock', verbose_name='message_block'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageflow_message_type', to='messageflow.MessageType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='botscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageflow.Scenario'),
        ),
        migrations.AddField(
            model_name='bot',
            name='scenario',
            field=models.ManyToManyField(through='messageflow.BotScenario', to='messageflow.Scenario'),
        ),
    ]
