# Generated by Django 2.0.5 on 2019-11-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='options',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True, verbose_name='options'),
        ),
    ]
