# Generated by Django 2.0.5 on 2019-10-10 02:11

from django.db import migrations, models
import django.db.models.deletion


def generate_message_type_rows(apps, schema_editor):
    MessageType = apps.get_model('messageflow', 'MessageType')

    trigger_type = MessageType()
    trigger_type.name = 'text'
    trigger_type.save()

    trigger_type = MessageType()
    trigger_type.name = 'option'
    trigger_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0002_auto_20191107_1255'),

    ]

    operations = [
        migrations.RunPython(generate_message_type_rows),
    ]
