# Generated by Django 2.0.5 on 2019-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0008_auto_20191119_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='app_id')),
                ('line_access_url_part', models.CharField(max_length=2048, null=True, verbose_name='line_access_url_part')),
                ('line_channel_access_token', models.CharField(max_length=2048, null=True, verbose_name='line_channel_access_token')),
                ('line_channel_secret', models.CharField(max_length=256, null=True, verbose_name='line_channel_secret')),
            ],
            options={
                'verbose_name': 'Settings',
                'permissions': (),
            },
        ),
    ]
