# Generated by Django 2.0.5 on 2019-10-10 02:11

from django.db import migrations, models
import django.db.models.deletion


def generate_dummy_scenario_for_targeted_messages(apps, schema_editor):
    Scenario = apps.get_model('messageflow', 'Scenario')

    scenario = Scenario()
    scenario.owner_id = -1
    scenario.app_id = "nchat"
    scenario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0002_auto_20191107_1255'),

    ]

    operations = [
        migrations.RunPython(generate_dummy_scenario_for_targeted_messages),
    ]
