# Generated by Django 2.0.5 on 2019-12-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0011_target_message_seed'),
        ('messageflow', '0010_auto_20191203_1212'),
    ]

    operations = [
    ]
