# Generated by Django 2.0.5 on 2019-12-12 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageflow', '0012_merge_20191205_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botscenario',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
