branch-defaults:
  default:
    environment: django-env
  main:
    environment: django-env
environment-defaults:
  django-env:
    branch: main
    repository: origin
global:
  application_name: django-tutorial
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
