# Generated by Django 2.0.5 on 2019-10-11 08:36

import apps.nchat.models.business
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0002_auto_20190903_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, max_length=2024, null=True, upload_to=apps.nchat.models.business.business_directory_path, verbose_name='logo'),
        ),
    ]
