# Generated by Django 2.0.5 on 2019-10-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0003_auto_20191018_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='duration in months'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='recurring',
            field=models.BooleanField(default=True, verbose_name='is recurring payment'),
        ),
    ]
