# Generated by Django 2.0.5 on 2019-10-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0003_auto_20191011_1736'),
        ('nchat', '0003_auto_20191018_1808'),
    ]

    operations = [
    ]
