# Generated by Django 2.0.5 on 2019-10-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0004_auto_20191021_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=256)),
                ('amount', models.BigIntegerField()),
                ('expiration_dt', models.DateTimeField(verbose_name='expiration datetime')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='regist datetime')),
                ('status', models.IntegerField(default=1, verbose_name='payment status')),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_business', to='nchat.Business')),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_business', to='nchat.Business')),
            ],
            options={
                'verbose_name': 'PaymentHistory',
                'permissions': (),
            },
        ),
    ]
