# Generated by Django 2.0.5 on 2019-10-22 06:39

from django.db import migrations
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0005_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='description',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
