# Generated by Django 2.0.5 on 2019-10-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0006_businessplan_description'),
        ('nchat', '0004_merge_20191030_1723'),
    ]

    operations = [
    ]
