# Generated by Django 2.0.5 on 2019-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0007_merge_20191030_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration in months'),
        ),
    ]
