# Generated by Django 2.0.5 on 2019-11-05 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0008_auto_20191101_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField(null=True, verbose_name='business')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nchat_settings_business', to='nchat.Business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Settings',
                'permissions': (),
            },
        ),
    ]
