# Generated by Django 2.0.5 on 2019-11-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('nchat', '0010_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('gender', models.CharField(max_length=25, null=True, verbose_name='gender')),
                ('birth_date', models.DateField(null=True, verbose_name='birth day')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='email')),
                ('tel', models.CharField(max_length=32, null=True, verbose_name='tel')),
                ('attribute_json', models.TextField(null=True, verbose_name='Attribute')),
                ('last_login_dt', models.DateTimeField(null=True, verbose_name='login datetime')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('subscribed', models.BooleanField(default=1, verbose_name='subscribe flg')),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='user_tag', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'EndUser',
                'permissions': (),
            },
        ),
    ]
