# Generated by Django 2.0.5 on 2019-11-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nchat', '0012_auto_20191113_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='tag',
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
    ]
