# Generated by Django 2.0.5 on 2018-06-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('mtg_period', models.CharField(max_length=64, null=True, verbose_name='MTG Period (minute)')),
                ('location', models.CharField(max_length=1024, null=True, verbose_name='location')),
                ('tel', models.CharField(max_length=64, null=True, verbose_name='tel')),
                ('is_pocket_time', models.BooleanField(default=0, verbose_name='pocket time flg')),
                ('gcl_keyword', models.CharField(max_length=64, null=True, verbose_name='google calender keyword')),
                ('attendance_num', models.IntegerField(null=True, verbose_name='number of attendances')),
                ('trigger_payload', models.CharField(default='RESERVATION_PAYLOAD', max_length=1028, null=True, verbose_name='trigger payload')),
                ('is_use_gcl', models.BooleanField(default=1, verbose_name='use google calender flg')),
                ('is_set_gcl', models.BooleanField(default=1, verbose_name='set google calender flg')),
                ('fixed_start_dt', models.DateTimeField(null=True, verbose_name='fixed schedule start datetime')),
                ('fixed_end_dt', models.DateTimeField(null=True, verbose_name='fixed schedule start datetime')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'Reservation',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(null=True, verbose_name='reserve_date')),
                ('reserve_start_time', models.TimeField(null=True, verbose_name='reserve_start_time')),
                ('reserve_end_time', models.TimeField(null=True, verbose_name='reserve_end_time')),
                ('google_calender_url', models.CharField(max_length=1024, null=True, verbose_name='google_calender_url')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('end_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationhistory_end_user', to='core.EndUser', verbose_name='end_user')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationhistory_reservation', to='core.Reservation', verbose_name='Reservation')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationhistory_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'ReservationHistory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Tag Category Name')),
                ('display_order_num', models.IntegerField(null=True, verbose_name='Display Order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagcategory_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'TagCategory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='last name')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='first name')),
                ('last_name_kana', models.CharField(max_length=64, null=True, verbose_name='last name kana')),
                ('first_name_kana', models.CharField(max_length=64, null=True, verbose_name='first name kana')),
                ('email', models.CharField(max_length=2048, null=True, verbose_name='email')),
                ('facebood_sender_id', models.CharField(max_length=256, null=True, verbose_name='sender id')),
                ('line_user_id', models.CharField(max_length=64, null=True, verbose_name='user_id')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendoruser_user', to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendoruser_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'VendorUser',
                'permissions': (),
            },
        ),
    ]
