# Generated by Django 2.0.5 on 2018-06-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_reservationhistory_tagcategory_vendoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=256, null=True, verbose_name='display_name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduserstate_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'EndUserState',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EndUserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaging_api_param_json', models.TextField(null=True, verbose_name='api parameter')),
                ('run_order_num', models.IntegerField(null=True, verbose_name='run order')),
                ('admin_text', models.TextField(null=True, verbose_name='memo for admin')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('end_user_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduserstory_end_user_state', to='core.EndUserState', verbose_name='end_user_state')),
            ],
            options={
                'verbose_name': 'EndUserStory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MessagingAPIType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=64, null=True, verbose_name='api category code')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='api category name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'MessagingAPIType',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, null=True, verbose_name='payload value')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payload_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'Payload',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='enduserstory',
            name='messaging_api_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduserstory_messaging_api_type', to='core.MessagingAPIType', verbose_name='messaging_api_type'),
        ),
        migrations.AddField(
            model_name='enduserstory',
            name='next_end_user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduserstory_next_end_user_state', to='core.EndUserState', verbose_name='next_end_user_state'),
        ),
        migrations.AddField(
            model_name='enduserstory',
            name='payload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduserstory_payload', to='core.Payload', verbose_name='payload'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='end_user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enduser_end_user_state', to='core.EndUserState', verbose_name='EndUserState'),
        ),
    ]
