# Generated by Django 2.0.5 on 2018-06-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180603_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomessageCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='condition name')),
                ('is_share', models.BooleanField(default=1, verbose_name='share flog for the same vendor')),
                ('display_order_num', models.IntegerField(null=True, verbose_name='Display Order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecondition_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'AutomessageCondition',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AutomessageController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaging_api_param_json', models.TextField(null=True, verbose_name='api parameter')),
                ('run_order_num', models.IntegerField(null=True, verbose_name='run order')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'AutomessageController',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AutomessageTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_days_num', models.IntegerField(null=True, verbose_name='trigger day before or after conditions')),
                ('is_trigger_after', models.BooleanField(default=1, verbose_name='Triggered after ')),
                ('trigger_time', models.TimeField(null=True, verbose_name='Trigger Schedule ')),
                ('title_name', models.CharField(max_length=128, null=True, verbose_name='Title for settings')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('automessage_condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagetrigger_automessage_condition', to='core.AutomessageCondition', verbose_name='automessage_condition')),
            ],
            options={
                'verbose_name': 'AutomessageTrigger',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='automessagecontroller',
            name='automessage_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_automessage_trigger', to='core.AutomessageTrigger', verbose_name='automessage_trigger'),
        ),
        migrations.AddField(
            model_name='automessagecontroller',
            name='messaging_api_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_messaging_api_type', to='core.MessagingAPIType', verbose_name='messaging_api_type'),
        ),
    ]
