# Generated by Django 2.0.5 on 2018-06-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180603_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_text', models.CharField(max_length=64, null=True, verbose_name='memo for admin')),
                ('send_dt', models.DateTimeField(null=True, verbose_name='sent datetime')),
                ('send_user_count', models.IntegerField(null=True, verbose_name='number of users')),
                ('send_user_id_csv', models.CharField(max_length=64, null=True, verbose_name='users sent')),
                ('selected_tag_csv', models.CharField(max_length=64, null=True, verbose_name='tag selected')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'AutoMessageHistory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AutoMessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='type name')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'AutoMessageType',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ManualMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_text', models.CharField(max_length=64, null=True, verbose_name='memo for admin')),
                ('send_dt', models.DateTimeField(null=True, verbose_name='sent datetime')),
                ('send_user_count', models.IntegerField(null=True, verbose_name='number of users')),
                ('send_user_id_csv', models.CharField(max_length=64, null=True, verbose_name='users sent')),
                ('selected_tag_csv', models.CharField(max_length=64, null=True, verbose_name='tag selected')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('manual_message_overview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualmessagehistory_manual_message_overview', to='core.ManualMessageOverview', verbose_name='manual_message_overview')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualmessagehistory_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'ManualMessageHistory',
                'permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='automessagecondition',
            options={'permissions': (), 'verbose_name': 'AutoMessageCondition'},
        ),
        migrations.AlterField(
            model_name='automessagecontroller',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagetrigger',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagetrigger_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AddField(
            model_name='automessagehistory',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AddField(
            model_name='automessagehistory',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AddField(
            model_name='automessagehistory',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch'),
        ),
        migrations.AddField(
            model_name='automessagecondition',
            name='auto_message_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecondition_auto_message_type', to='core.AutoMessageType', verbose_name='auto_message_type'),
        ),
    ]
