# Generated by Django 2.0.5 on 2018-06-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180608_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('url', models.CharField(max_length=2048, null=True, verbose_name='Web site URL')),
                ('location', models.CharField(max_length=1024, null=True, verbose_name='location')),
                ('tel', models.CharField(max_length=64, null=True, verbose_name='tel')),
                ('is_public', models.BooleanField(default=0, verbose_name='public flg')),
                ('capacity_num', models.IntegerField(null=True, verbose_name='number of capacity')),
                ('is_gcal_set', models.BooleanField(default=1, verbose_name='set google calender flg')),
                ('start_dt', models.DateTimeField(null=True, verbose_name='fixed schedule start datetime')),
                ('end_dt', models.DateTimeField(null=True, verbose_name='fixed schedule start datetime')),
                ('gcal_keyword', models.CharField(max_length=64, null=True, verbose_name='google calender keyword')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
            ],
            options={
                'verbose_name': 'Event',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('display_order_num', models.IntegerField(null=True, verbose_name='Display Order')),
                ('is_public', models.BooleanField(default=0, verbose_name='public flg')),
                ('is_gcal_use', models.BooleanField(default=1, verbose_name='use google calender flg')),
                ('is_gcal_available_time', models.BooleanField(default=0, verbose_name='available time flg')),
                ('is_user_select_event_minutes', models.BooleanField(default=0, verbose_name='user can select the event minutes')),
                ('event_minutes_csv', models.CharField(max_length=64, null=True, verbose_name='Event Minutes (CSV) ')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventcategory_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'EventCategory',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(null=True, verbose_name='reservation_date')),
                ('reservation_start_time', models.TimeField(null=True, verbose_name='reservation_start_time')),
                ('reservation_end_time', models.TimeField(null=True, verbose_name='reservation_end_time')),
                ('gcal_url', models.CharField(max_length=1024, null=True, verbose_name='google_calender_url')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('end_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventreservation_end_user', to='core.EndUser', verbose_name='end_user')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventreservation_event', to='core.Event', verbose_name='event')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventreservation_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'EventReservation',
                'permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_event',
        ),
        migrations.RemoveField(
            model_name='reservationevent',
            name='vendor_branch',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='end_user',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='vendor_branch',
        ),
        migrations.AlterField(
            model_name='automessagecontroller',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagetrigger',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagetrigger_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationEvent',
        ),
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_category', to='core.EventCategory', verbose_name='event_category'),
        ),
    ]
