# Generated by Django 2.0.5 on 2018-06-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180613_1454'),
        ('core', '0033_auto_20180614_1504'),
    ]

    operations = [
    ]
