# Generated by Django 2.0.5 on 2018-06-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20180614_2222'),
        ('core', '0034_auto_20180614_1806'),
    ]

    operations = [
    ]
