# Generated by Django 2.0.5 on 2018-07-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20180702_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserstorytemplate',
            name='end_user_state',
            field=models.CharField(max_length=256, null=True, verbose_name='end_user_state'),
        ),
        migrations.AlterField(
            model_name='automessagecontroller',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagetrigger',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagetrigger_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AlterField(
            model_name='enduserstorytemplate',
            name='messaging_api_param_json',
            field=models.TextField(null=True, verbose_name='messaging_api_param_json'),
        ),
        migrations.AlterField(
            model_name='enduserstorytemplate',
            name='messaging_api_type',
            field=models.CharField(max_length=256, null=True, verbose_name='messaging_api_type'),
        ),
        migrations.AlterField(
            model_name='enduserstorytemplate',
            name='next_end_user_state',
            field=models.CharField(max_length=256, null=True, verbose_name='next_end_user_state'),
        ),
        migrations.AlterField(
            model_name='enduserstorytemplatecategory',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
    ]
