# Generated by Django 2.0.5 on 2018-07-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180709_1127'),
        ('core', '0052_auto_20180709_2123'),
    ]

    operations = [
    ]
