# Generated by Django 2.0.5 on 2018-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20180713_1511'),
        ('core', '0058_auto_20180713_1150'),
    ]

    operations = [
    ]
