# Generated by Django 2.0.5 on 2018-08-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20180731_1017'),
        ('core', '0072_auto_20180801_1703'),
    ]

    operations = [
    ]
