# Generated by Django 2.0.5 on 2018-08-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20180802_1654'),
        ('core', '0073_merge_20180802_0948'),
    ]

    operations = [
    ]
