# Generated by Django 2.0.5 on 2018-10-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20180919_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryLogEndUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user_id', models.IntegerField(null=True, verbose_name='End User ID')),
                ('device_type', models.IntegerField(null=True, verbose_name='Device Type')),
                ('device_family', models.CharField(max_length=64, null=True, verbose_name='Device Family')),
                ('os_family', models.CharField(max_length=64, null=True, verbose_name='OS Family ')),
                ('os_version', models.CharField(max_length=64, null=True, verbose_name='OS Version ')),
                ('browser_family', models.CharField(max_length=64, null=True, verbose_name='Browser Family ')),
                ('browser_version', models.CharField(max_length=64, null=True, verbose_name='Browser Version ')),
                ('ip_address', models.CharField(max_length=64, null=True, verbose_name='IP Address ')),
                ('server_host', models.CharField(max_length=64, null=True, verbose_name='Server HOST ')),
                ('status_code', models.CharField(max_length=64, null=True, verbose_name='Status Code ')),
                ('content_type', models.CharField(max_length=64, null=True, verbose_name='Content Type ')),
                ('http_referer', models.CharField(max_length=1024, null=True, verbose_name='Http Referer ')),
                ('action_type', models.CharField(max_length=64, null=True, verbose_name='Action Type')),
                ('params', models.CharField(max_length=1024, null=True, verbose_name='Params')),
                ('endpoint', models.CharField(max_length=1024, null=True, verbose_name='Server HOST ')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarylogendusers_service', to='core.Service', verbose_name='service')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarylogendusers_vendor', to='core.Vendor', verbose_name='vendor')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarylogendusers_vendor_branch', to='core.VendorBranch', verbose_name='vendor_branch')),
            ],
            options={
                'verbose_name': 'SummaryLogEndUser',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SummaryLogVendorUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.IntegerField(null=True, verbose_name='Device Type')),
                ('device_family', models.CharField(max_length=64, null=True, verbose_name='Device Family')),
                ('os_family', models.CharField(max_length=64, null=True, verbose_name='OS Family ')),
                ('os_version', models.CharField(max_length=64, null=True, verbose_name='OS Version ')),
                ('browser_family', models.CharField(max_length=64, null=True, verbose_name='Browser Family ')),
                ('browser_version', models.CharField(max_length=64, null=True, verbose_name='Browser Version ')),
                ('ip_address', models.CharField(max_length=64, null=True, verbose_name='IP Address ')),
                ('server_host', models.CharField(max_length=64, null=True, verbose_name='Server HOST ')),
                ('status_code', models.CharField(max_length=64, null=True, verbose_name='Status Code ')),
                ('content_type', models.CharField(max_length=64, null=True, verbose_name='Content Type ')),
                ('http_referer', models.CharField(max_length=1024, null=True, verbose_name='Http Referer ')),
                ('action_type', models.CharField(max_length=64, null=True, verbose_name='Action Type')),
                ('params', models.CharField(max_length=1024, null=True, verbose_name='Params')),
                ('endpoint', models.CharField(max_length=1024, null=True, verbose_name='Server HOST ')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='regist datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='update datetime')),
                ('is_delete', models.BooleanField(default=0, verbose_name='delete flg')),
                ('vendor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarylogvendorusers_vendor_user', to='core.VendorUser', verbose_name='vendor_user')),
            ],
            options={
                'verbose_name': 'SummaryLogVendorUser',
                'permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='automessagecontroller',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagecontroller_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
        migrations.AlterField(
            model_name='automessagehistory',
            name='auto_message_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagehistory_auto_message_trigger', to='core.AutoMessageTrigger', verbose_name='auto_message_trigger'),
        ),
        migrations.AlterField(
            model_name='automessagetrigger',
            name='auto_message_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automessagetrigger_auto_message_condition', to='core.AutoMessageCondition', verbose_name='auto_message_condition'),
        ),
    ]
