# Generated by Django 2.0.5 on 2018-11-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20181029_1842'),
        ('core', '0082_auto_20181012_1654'),
    ]

    operations = [
    ]
