# Generated by Django 2.0.5 on 2018-10-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20181016_1652'),
        ('core', '0090_auto_20181029_1842'),
    ]

    operations = [
    ]
