# Generated by Django 2.0.5 on 2018-11-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20181101_1436'),
        ('core', '0093_auto_20181101_1329'),
    ]

    operations = [
    ]
