# Generated by Django 2.0.5 on 2018-11-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_todo_message_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoruser',
            name='email',
            field=models.CharField(default='hoge', max_length=255, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
