# Generated by Django 2.0.5 on 2018-11-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20181128_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoruser',
            old_name='facebood_sender_id',
            new_name='facebook_sender_id',
        ),
    ]
