# Generated by Django 2.0.5 on 2018-11-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_vendor_user_rename_facebook_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoruser',
            name='email',
            field=models.CharField(max_length=255, null=True, blank=False, unique=True, verbose_name='email'),
        ),
    ]
