# Generated by Django 2.0.5 on 2018-11-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20181128_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contactchat_verify_token',
            field=models.CharField(default='qwerty', max_length=256, verbose_name='ContactChat Verify Token'),
        ),
    ]
