# Generated by Django 2.0.5 on 2019-05-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20190420_2213'),
        ('core', '0130_auto_20190422_1725'),
    ]

    operations = [
    ]
