# Generated by Django 2.0.5 on 2019-10-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20190903_1121'),
        ('core', '0178_auto_20190925_1316'),
    ]

    operations = [
    ]
