# Generated by Django 2.0.5 on 2019-10-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_merge_20191003_1726'),
        ('core', '0179_auto_20190909_1418'),
    ]

    operations = [
    ]
