# Generated by Django 2.0.5 on 2019-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_auto_20191011_1737'),
        ('core', '0184_auto_20191018_1808'),
    ]

    operations = [
    ]
