# Generated by Django 2.0.5 on 2019-10-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20191022_1540'),
        ('core', '0186_merge_20191030_1754'),
    ]

    operations = [
    ]
