# Generated by Django 2.0.5 on 2019-11-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_auto_20191111_1027'),
        ('core', '0208_auto_20191112_1534'),
    ]

    operations = [
    ]
