# Generated by Django 2.0.5 on 2021-06-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_auto_20210617_1003'),
        ('core', '0214_auto_20210617_0226'),
    ]

    operations = [
    ]
