# Generated by Django 2.0.5 on 2019-10-01 05:10

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, verbose_name='days')),
                ('hours', models.IntegerField(default=0, verbose_name='days')),
            ],
            options={
                'verbose_name': 'MaTrigger',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MaTriggerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ma trigger type name')),
            ],
            options={
                'verbose_name': 'MaTriggerType',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='message subject')),
                ('message_text', froala_editor.fields.FroalaField()),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='owner_id')),
            ],
            options={
                'verbose_name': 'Message',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='matrigger',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailroom_matrigger_message', to='mailroom.Message', verbose_name='message'),
        ),
        migrations.AddField(
            model_name='matrigger',
            name='trigger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailroom_matrigger_trigger_type', to='mailroom.MaTriggerType', verbose_name='trigger_type'),
        ),
    ]
