# Generated by Django 2.0.5 on 2019-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0002_auto_20191001_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='app_id',
        ),
        migrations.AddField(
            model_name='message',
            name='app_id2',
            field=models.CharField(default=123, max_length=256, verbose_name='app_id2'),
            preserve_default=False,
        ),
    ]
