# Generated by Django 2.0.5 on 2019-10-02 06:46

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0004_auto_20191001_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='message subject')),
                ('recipients', models.CharField(max_length=512, null=True, verbose_name='message recipients')),
                ('message_text', froala_editor.fields.FroalaField()),
                ('owner_id', models.IntegerField(verbose_name='owner_id')),
                ('app_id', models.CharField(max_length=256, verbose_name='app_id')),
            ],
            options={
                'verbose_name': 'MessageHistory',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.CharField(max_length=512, null=True, verbose_name='message recipients'),
        ),
    ]
