# Generated by Django 2.0.5 on 2019-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0007_auto_20191008_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=256, verbose_name='message template name'),
        ),
        migrations.AlterField(
            model_name='messagetemplatecategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='message template category name'),
        ),
    ]
