# Generated by Django 2.0.5 on 2019-10-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0009_auto_20191008_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='valid_until',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='valid until datetime'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailroom_message', to='mailroom.Message', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='mailroom.MessageTemplateCategory', verbose_name='template_category'),
        ),
    ]
