# Generated by Django 2.0.5 on 2019-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0010_auto_20191009_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='status',
            field=models.IntegerField(null=True, verbose_name='owner_id'),
        ),
    ]
