# Generated by Django 2.0.5 on 2019-10-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0011_messagehistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='valid_until',
            new_name='date',
        ),
    ]
