# Generated by Django 2.0.5 on 2019-10-10 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0013_auto_20191009_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='recipients',
            field=models.TextField(blank=True, default='', verbose_name='message recipients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='send_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='send_dt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
            preserve_default=False,
        ),
    ]
