# Generated by Django 2.0.5 on 2019-10-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0014_auto_20191010_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='send_dt',
        ),
    ]
