# Generated by Django 2.0.5 on 2019-10-10 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailroom', '0015_remove_messagehistory_send_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='send_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='send_dt'),
            preserve_default=False,
        ),
    ]
